apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: node-red
  name: node-red-pvc
  namespace: nodered
spec:
  volumeName: nodered-pv
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
status: {}