apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodered
  name: nodered
  namespace: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodered
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - image: nodered/node-red:latest
          imagePullPolicy: IfNotPresent
          name: nodered
          ports:
            - containerPort: 1880
              name: nodered-tcp
              protocol: TCP
            - containerPort: 80
              name: alexa-port
              protocol: TCP
            - containerPort: 3455
          resources: {}
          env:
            - name: TZ
              value: Europe/Rome
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: process.env.PORT
              value: "10880"
          volumeMounts:
            - mountPath: /data
              name: nodered-pvc
              subPath: _nodered
      volumes:
        - name: nodered-pvc
          persistentVolumeClaim:
            claimName: node-red-pvc