apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodered
  name: nodered
  namespace: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodered
      name: nodered
    spec:
      terminationGracePeriodSeconds: 30
      hostNetwork: false
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: nodered
          image: nodered/node-red
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          ports:
            - containerPort: 1880
              name: nodered-tcp
              protocol: TCP
            - containerPort: 48180
              name: alexa-port
              protocol: TCP
            - containerPort: 3455
              name: port-3455
              protocol: TCP
            - containerPort: 34568
              name: alexa-token-prt
              protocol: TCP
          env:
            - name: TZ
              value: Europe/Rome
            - name: process.env.PORT
              value: "10880"
          volumeMounts:
            - mountPath: /data
              name: nodered-pvc
              subPath: _nodered
      volumes:
        - name: nodered-pvc
          persistentVolumeClaim:
            claimName: node-red-pvc