---
apiVersion: v1
kind: Service
metadata:
  name: nodered-tcp
  namespace: nodered
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: "nodered"
spec:
  selector:
    app: nodered
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.0.238
  ports:
  - port: 80
    targetPort: 1880
    name: nodered-gui
  type: LoadBalancer
