apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  namespace: pihole
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: "pihole"
spec:
  selector:
    app: pihole
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.0.240
  ports:
      # pihole use Ports to expose (53, 80, 67, 443), the bare minimum ports required for Pi-holes HTTP and DNS services
      - port: 48080
        targetPort: pihole-http
        name: pihole-http
        protocol: TCP
      - port: 48443
        targetPort: pihole-ssl
        name: port443
        protocol: TCP
      - port: 53
        targetPort: pihole-dns
        protocol: TCP
        name: port53
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  namespace: pihole
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: "pihole"
spec:
  selector:
    app: pihole
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.0.240
  ports:
      - port: 53
        targetPort: pihole-dns-udp
        protocol: UDP
        name: port53-udp
      - port: 67
        targetPort: client-udp
        protocol: UDP
        name: port67-udp