apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pihole
  namespace: pihole
spec:
  volumeName: pv-pihole
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 300M