apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.100
    # Exported path of your NFS server
    path: "/volume1/k3s-data/pihole/config"
    