apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-data-pvc
  namespace: homebridge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 500Mi
 