apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-data-pvc
  namespace: homebridge
spec:
  volumeName: homebridge-pv
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-pvc
  namespace: homebridge
spec:
  volumeName: homebridge
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi