apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-pvc
  namespace: homebridge
spec:
  volumeName: homebridge-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi