apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homebridge-ingress
  namespace: homebridge
  annotations:
    #traefik.ingress.kubernetes.io/router.entrypoints: web
    # traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    traefik.ingress.kubernetes.io/router.middlewares: default-nodered-middleware@kubernetescrd

spec:
  rules:
    - http: 
        paths:
          - path: /homebridge
            pathType: Prefix
            backend:
              service:
                name: homebridge-service
                port:
                  number: 40080
