apiVersion: v1
kind: Service
metadata:
  name: homebridge-http
  namespace: homebridge
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: "homebridge"
spec:
  selector:
    app: homebridge
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.0.239
  ports:
  - port: 80
    targetPort: homebridge-http
    name: homebridge-gui
  type: LoadBalancer