apiVersion: v1
kind: Service
metadata:
  name: homebridge-http
  namespace: homebridge
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: "homebridge"
spec:
  selector:
    app: homebridge
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.0.235
  ports:
  - port: 80
    targetPort: homebridge-port
    name: homebridge-gui
  - port: 53055
    targetPort: homebridge-srv
    name: homebridge-srv
  type: LoadBalancer