apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebridge
  namespace: homebridge
  labels:
    app: homebridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
      name: homebridge
    spec:
      securityContext:
        fsGroup: 2000
      #hostNetwork: true
      #dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: homebridge
        image: oznu/homebridge:no-avahi-arm32v6
        imagePullPolicy: Always
        ports:
        - containerPort: 8581
          name: homebridge-http
        - containerPort: 51828
          name: webhook
        env:
        - name: tz
          value: 'Europe/Rome'
        # You can change these to ID values to 1000 (ubuntu user) if not using Bluetooth
        # - name: PUID
        #   value: '0'
        # - name: PGID
        #   value: '0'
        - name: HOMEBRIDGE_CONFIG_UI
          value: '1'
        - name: HOMEBRIDGE_CONFIG_UI_PORT
          value: '8581'
        volumeMounts:
        - name: homebridge
          mountPath: /homebridge
          readOnly: false
      volumes:
      - name: homebridge
        persistentVolumeClaim:
          claimName: homebridge-data-pvc