apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-data-pvc
  namespace: homebridge
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rasp4-local-storage
  resources:
    requests:
      storage: 1Gi