apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-data-pvc
  namespace: homebridge
spec:
  volumeName: homebridge-data-pv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Mi