apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homebridge
  name: homebridge
  namespace: homebridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebridge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: homebridge
      name: homebridge
    spec:
      terminationGracePeriodSeconds: 30
      #hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: homebridge
        image: oznu/homebridge:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 18581
          name: homebridge-port
        - containerPort: 53055
          name: homebridge-srv
        - containerPort: 58891
          name: shelly
        - containerPort: 52587
          name: bridge-prt
        - containerPort: 51828
          name: webhooks-prt
        resources: {}
        env:
        - name: tz
          value: 'Europe/Rome'
        - name: HOMEBRIDGE_CONFIG_UI
          value: '1'
        - name: HOMEBRIDGE_CONFIG_UI_PORT
          value: '18581'
        volumeMounts:
        - name: homebridge
          mountPath: /homebridge
          subPath: _homebridge
      volumes:
      - name: homebridge
        persistentVolumeClaim:
          claimName: homebridge-pvc