apiVersion: v1
kind: Service
metadata:
  name: homebridge-service
  namespace: homebridge
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: "homebridge"
spec:
  selector:
    app: homebridge
  externalTrafficPolicy: Local
  #loadBalancerIP: 192.168.0.235
  ports:
  - port: 40080
    targetPort: homebridge-port
    name: homebridge-gui
  # - port: 58891
  #   targetPort: shelly
  #   name: shelly
  type: LoadBalancer