apiVersion: v1
kind: PersistentVolume
metadata:
  name: homebridge-data-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.100
    # Exported path of your NFS server
    path: "/volume1/k3s-data/homebridge"
    