apiVersion: v1
kind: Service
metadata:
  name: argocd-service
  namespace: argocd
  annotations:
    metallb.universe.tf/allow-shared-ip: "argocd"
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.0.240
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080