apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  local:
    path: /home/pi/usb-hdd
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rasp4modb
  # nfs:
  #   server: 192.168.1.100
  #   # Exported path of your NFS server
  #   path: "/volume1/k3s/shared"
    