apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.0.230-192.168.0.240
    - name: network-services
      protocol: layer2
      addresses:
      - 192.168.0.241-192.168.0.250