apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-data-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.100
    # Exported path of your NFS server
    path: "/volume1/k3s-data/mosquitto/data"
    