kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-data-pvc
  namespace: iot
spec:
  volumeName: mosquitto-data-pv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi