apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mosquitto
  name: mosquitto-pvc
  namespace: mosquitto
spec:
  volumeName: mosquitto-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi