---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: mosquitto
  # annotations:
  #   metallb.universe.tf/address-pool: default
  #   metallb.universe.tf/allow-shared-ip: "mosquitto"
spec:
  selector:
    app: mosquitto
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
      - port: 1883
        targetPort: mosq-prt
        name: mosquitto-tcp
        protocol: TCP