apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: mosquitto
  annotations:
    metallb.universe.tf/allow-shared-ip: "mosquitto"
spec:
  selector:
    app: mosquitto
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.0.245
  ports:
      - port: 1883
        targetPort: mosq-prt
        name: mosquitto-tcp
        protocol: TCP