apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Gi
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.100
    path: "/volume1/k3s-data"