resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml

namespace: longhorn-system

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          storage: longhorn
  - target:
      kind: DaemonSet
      name: longhorn-manager
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value: 
          storage: longhorn
