resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml

namespace: longhorn-system

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          storage: longhorn
  - target:
      kind: DaemonSet
      name: longhorn-manager
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value: 
          storage: longhorn
  - target:
      kind: Service
      name: longhorn-frontend
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /spec/loadBalancerIP
        value: 192.168.0.241
